<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <ApplicationVersion>1.0.0.0</ApplicationVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>oscilloscope.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Oscilloscope\OscilloscopeLib.csproj" />
    <Content Include="oscilloscope.ico" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>